#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 87
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 62
#define ALIAS_COUNT 1
#define TOKEN_COUNT 33
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 5
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 7

enum {
  anon_sym_SLASH_SLASH = 1,
  aux_sym_comment_token1 = 2,
  aux_sym_comment_token2 = 3,
  anon_sym_LT_DASH = 4,
  anon_sym_EQ = 5,
  anon_sym_SLASH = 6,
  anon_sym_COLON = 7,
  anon_sym_AMP = 8,
  anon_sym_BANG = 9,
  anon_sym_QMARK = 10,
  anon_sym_STAR = 11,
  anon_sym_PLUS = 12,
  anon_sym_LPAREN = 13,
  anon_sym_RPAREN = 14,
  anon_sym_DOT = 15,
  sym_identifier = 16,
  anon_sym_i = 17,
  aux_sym__sq_string_literal_token1 = 18,
  aux_sym__sq_string_literal_token2 = 19,
  anon_sym_DQUOTE = 20,
  aux_sym__dq_string_literal_token1 = 21,
  anon_sym_LBRACK = 22,
  anon_sym_RBRACK = 23,
  anon_sym_DASH = 24,
  aux_sym__char_token1 = 25,
  aux_sym_escape_token1 = 26,
  aux_sym_escape_token2 = 27,
  aux_sym_escape_token3 = 28,
  aux_sym_escape_token4 = 29,
  anon_sym_LBRACE = 30,
  anon_sym_RBRACE = 31,
  aux_sym__code_token1 = 32,
  sym_grammar = 33,
  sym_comment = 34,
  sym_definition = 35,
  sym_expression = 36,
  sym__sequence = 37,
  sym_alias = 38,
  sym_term = 39,
  sym_prefix = 40,
  sym_suffix = 41,
  sym_primary = 42,
  sym_e = 43,
  sym_literal = 44,
  sym__sq_string_literal = 45,
  sym__dq_string_literal = 46,
  sym_class = 47,
  sym__range = 48,
  sym__char = 49,
  sym_escape = 50,
  sym_action = 51,
  sym__code = 52,
  aux_sym_grammar_repeat1 = 53,
  aux_sym_expression_repeat1 = 54,
  aux_sym__sequence_repeat1 = 55,
  aux_sym_e_repeat1 = 56,
  aux_sym__sq_string_literal_repeat1 = 57,
  aux_sym__dq_string_literal_repeat1 = 58,
  aux_sym__range_repeat1 = 59,
  aux_sym__range_repeat2 = 60,
  aux_sym_action_repeat1 = 61,
  alias_sym_name = 62,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SLASH_SLASH] = "//",
  [aux_sym_comment_token1] = "comment_token1",
  [aux_sym_comment_token2] = "comment_token2",
  [anon_sym_LT_DASH] = "<-",
  [anon_sym_EQ] = "=",
  [anon_sym_SLASH] = "/",
  [anon_sym_COLON] = ":",
  [anon_sym_AMP] = "&",
  [anon_sym_BANG] = "!",
  [anon_sym_QMARK] = "\?",
  [anon_sym_STAR] = "*",
  [anon_sym_PLUS] = "+",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_DOT] = ".",
  [sym_identifier] = "identifier",
  [anon_sym_i] = "i",
  [aux_sym__sq_string_literal_token1] = "_sq_string_literal_token1",
  [aux_sym__sq_string_literal_token2] = "_sq_string_literal_token2",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym__dq_string_literal_token1] = "_dq_string_literal_token1",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_DASH] = "-",
  [aux_sym__char_token1] = "_char_token1",
  [aux_sym_escape_token1] = "escape_token1",
  [aux_sym_escape_token2] = "escape_token2",
  [aux_sym_escape_token3] = "escape_token3",
  [aux_sym_escape_token4] = "escape_token4",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [aux_sym__code_token1] = "_code_token1",
  [sym_grammar] = "grammar",
  [sym_comment] = "comment",
  [sym_definition] = "definition",
  [sym_expression] = "expression",
  [sym__sequence] = "_sequence",
  [sym_alias] = "alias",
  [sym_term] = "term",
  [sym_prefix] = "prefix",
  [sym_suffix] = "suffix",
  [sym_primary] = "primary",
  [sym_e] = "e",
  [sym_literal] = "literal",
  [sym__sq_string_literal] = "_sq_string_literal",
  [sym__dq_string_literal] = "_dq_string_literal",
  [sym_class] = "class",
  [sym__range] = "_range",
  [sym__char] = "_char",
  [sym_escape] = "escape",
  [sym_action] = "action",
  [sym__code] = "_code",
  [aux_sym_grammar_repeat1] = "grammar_repeat1",
  [aux_sym_expression_repeat1] = "expression_repeat1",
  [aux_sym__sequence_repeat1] = "_sequence_repeat1",
  [aux_sym_e_repeat1] = "e_repeat1",
  [aux_sym__sq_string_literal_repeat1] = "_sq_string_literal_repeat1",
  [aux_sym__dq_string_literal_repeat1] = "_dq_string_literal_repeat1",
  [aux_sym__range_repeat1] = "_range_repeat1",
  [aux_sym__range_repeat2] = "_range_repeat2",
  [aux_sym_action_repeat1] = "action_repeat1",
  [alias_sym_name] = "name",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SLASH_SLASH] = anon_sym_SLASH_SLASH,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [aux_sym_comment_token2] = aux_sym_comment_token2,
  [anon_sym_LT_DASH] = anon_sym_LT_DASH,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_AMP] = anon_sym_AMP,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_identifier] = sym_identifier,
  [anon_sym_i] = anon_sym_i,
  [aux_sym__sq_string_literal_token1] = aux_sym__sq_string_literal_token1,
  [aux_sym__sq_string_literal_token2] = aux_sym__sq_string_literal_token2,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym__dq_string_literal_token1] = aux_sym__dq_string_literal_token1,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_DASH] = anon_sym_DASH,
  [aux_sym__char_token1] = aux_sym__char_token1,
  [aux_sym_escape_token1] = aux_sym_escape_token1,
  [aux_sym_escape_token2] = aux_sym_escape_token2,
  [aux_sym_escape_token3] = aux_sym_escape_token3,
  [aux_sym_escape_token4] = aux_sym_escape_token4,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [aux_sym__code_token1] = aux_sym__code_token1,
  [sym_grammar] = sym_grammar,
  [sym_comment] = sym_comment,
  [sym_definition] = sym_definition,
  [sym_expression] = sym_expression,
  [sym__sequence] = sym__sequence,
  [sym_alias] = sym_alias,
  [sym_term] = sym_term,
  [sym_prefix] = sym_prefix,
  [sym_suffix] = sym_suffix,
  [sym_primary] = sym_primary,
  [sym_e] = sym_e,
  [sym_literal] = sym_literal,
  [sym__sq_string_literal] = sym__sq_string_literal,
  [sym__dq_string_literal] = sym__dq_string_literal,
  [sym_class] = sym_class,
  [sym__range] = sym__range,
  [sym__char] = sym__char,
  [sym_escape] = sym_escape,
  [sym_action] = sym_action,
  [sym__code] = sym__code,
  [aux_sym_grammar_repeat1] = aux_sym_grammar_repeat1,
  [aux_sym_expression_repeat1] = aux_sym_expression_repeat1,
  [aux_sym__sequence_repeat1] = aux_sym__sequence_repeat1,
  [aux_sym_e_repeat1] = aux_sym_e_repeat1,
  [aux_sym__sq_string_literal_repeat1] = aux_sym__sq_string_literal_repeat1,
  [aux_sym__dq_string_literal_repeat1] = aux_sym__dq_string_literal_repeat1,
  [aux_sym__range_repeat1] = aux_sym__range_repeat1,
  [aux_sym__range_repeat2] = aux_sym__range_repeat2,
  [aux_sym_action_repeat1] = aux_sym_action_repeat1,
  [alias_sym_name] = alias_sym_name,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SLASH_SLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LT_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_i] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__sq_string_literal_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__sq_string_literal_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__dq_string_literal_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__char_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_escape_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_escape_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_escape_token3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_escape_token4] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__code_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_grammar] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym__sequence] = {
    .visible = false,
    .named = true,
  },
  [sym_alias] = {
    .visible = true,
    .named = true,
  },
  [sym_term] = {
    .visible = true,
    .named = true,
  },
  [sym_prefix] = {
    .visible = true,
    .named = true,
  },
  [sym_suffix] = {
    .visible = true,
    .named = true,
  },
  [sym_primary] = {
    .visible = true,
    .named = true,
  },
  [sym_e] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [sym__sq_string_literal] = {
    .visible = false,
    .named = true,
  },
  [sym__dq_string_literal] = {
    .visible = false,
    .named = true,
  },
  [sym_class] = {
    .visible = true,
    .named = true,
  },
  [sym__range] = {
    .visible = false,
    .named = true,
  },
  [sym__char] = {
    .visible = false,
    .named = true,
  },
  [sym_escape] = {
    .visible = true,
    .named = true,
  },
  [sym_action] = {
    .visible = true,
    .named = true,
  },
  [sym__code] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_grammar_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__sequence_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_e_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__sq_string_literal_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__dq_string_literal_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__range_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__range_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_action_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_name] = {
    .visible = true,
    .named = true,
  },
};

enum {
  field_explaination = 1,
  field_identifier = 2,
  field_prefix = 3,
  field_primary = 4,
  field_suffix = 5,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_explaination] = "explaination",
  [field_identifier] = "identifier",
  [field_prefix] = "prefix",
  [field_primary] = "primary",
  [field_suffix] = "suffix",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 2},
  [6] = {.index = 8, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_identifier, 0},
  [1] =
    {field_primary, 0},
  [2] =
    {field_primary, 0},
    {field_suffix, 1},
  [4] =
    {field_prefix, 0},
    {field_primary, 1},
  [6] =
    {field_explaination, 1},
    {field_identifier, 0},
  [8] =
    {field_prefix, 0},
    {field_primary, 1},
    {field_suffix, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [5] = {
    [1] = alias_sym_name,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  sym_literal, 2,
    sym_literal,
    alias_sym_name,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 41,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 11,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 63,
  [67] = 67,
  [68] = 14,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 71,
  [73] = 64,
  [74] = 18,
  [75] = 65,
  [76] = 20,
  [77] = 17,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 41,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(12);
      if (lookahead == '!') ADVANCE(22);
      if (lookahead == '"') ADVANCE(35);
      if (lookahead == '&') ADVANCE(21);
      if (lookahead == '\'') ADVANCE(32);
      if (lookahead == '(') ADVANCE(26);
      if (lookahead == ')') ADVANCE(27);
      if (lookahead == '*') ADVANCE(24);
      if (lookahead == '+') ADVANCE(25);
      if (lookahead == '-') ADVANCE(40);
      if (lookahead == '.') ADVANCE(28);
      if (lookahead == '/') ADVANCE(19);
      if (lookahead == ':') ADVANCE(20);
      if (lookahead == '<') ADVANCE(7);
      if (lookahead == '=') ADVANCE(18);
      if (lookahead == '?') ADVANCE(23);
      if (lookahead == '[') ADVANCE(38);
      if (lookahead == '\\') ADVANCE(9);
      if (lookahead == ']') ADVANCE(39);
      if (lookahead == 'i') ADVANCE(31);
      if (lookahead == '{') ADVANCE(50);
      if (lookahead == '}') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1)
      if (lookahead == '\\') ADVANCE(43);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(45);
      if (lookahead != 0) ADVANCE(41);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(2)
      if (lookahead == '\\') ADVANCE(43);
      if (lookahead == ']') ADVANCE(39);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(44);
      if (lookahead != 0) ADVANCE(41);
      END_STATE();
    case 3:
      if (lookahead == '\n') SKIP(3)
      if (lookahead == '-') ADVANCE(40);
      if (lookahead == '\\') ADVANCE(43);
      if (lookahead == ']') ADVANCE(39);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(42);
      if (lookahead != 0) ADVANCE(41);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(4)
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(35);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(37);
      if (lookahead != 0) ADVANCE(36);
      END_STATE();
    case 6:
      if (lookahead == '\'') ADVANCE(32);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(34);
      if (lookahead != 0) ADVANCE(33);
      END_STATE();
    case 7:
      if (lookahead == '-') ADVANCE(17);
      END_STATE();
    case 8:
      if (lookahead == '<') ADVANCE(7);
      if (lookahead == '=') ADVANCE(18);
      if (lookahead == 'i') ADVANCE(30);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(8)
      END_STATE();
    case 9:
      if (lookahead == '\\') ADVANCE(49);
      if (lookahead == ']') ADVANCE(47);
      if (lookahead == 'a') ADVANCE(46);
      if (lookahead == 'b') ADVANCE(48);
      END_STATE();
    case 10:
      if (lookahead == '{') ADVANCE(50);
      if (lookahead == '}') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(53);
      if (lookahead != 0) ADVANCE(52);
      END_STATE();
    case 11:
      if (eof) ADVANCE(12);
      if (lookahead == '!') ADVANCE(22);
      if (lookahead == '"') ADVANCE(35);
      if (lookahead == '&') ADVANCE(21);
      if (lookahead == '\'') ADVANCE(32);
      if (lookahead == '(') ADVANCE(26);
      if (lookahead == ')') ADVANCE(27);
      if (lookahead == '*') ADVANCE(24);
      if (lookahead == '+') ADVANCE(25);
      if (lookahead == '.') ADVANCE(28);
      if (lookahead == '/') ADVANCE(19);
      if (lookahead == ':') ADVANCE(20);
      if (lookahead == '<') ADVANCE(7);
      if (lookahead == '=') ADVANCE(18);
      if (lookahead == '?') ADVANCE(23);
      if (lookahead == '[') ADVANCE(38);
      if (lookahead == '{') ADVANCE(50);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(11)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(15);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      if (lookahead == '\n') ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LT_DASH);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '/') ADVANCE(13);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_AMP);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_QMARK);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_i);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_i);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym__sq_string_literal_token1);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym__sq_string_literal_token2);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym__sq_string_literal_token2);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(34);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(33);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym__dq_string_literal_token1);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym__dq_string_literal_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(37);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(36);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym__char_token1);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym__char_token1);
      if (lookahead == '-') ADVANCE(40);
      if (lookahead == '\\') ADVANCE(43);
      if (lookahead == ']') ADVANCE(39);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(41);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym__char_token1);
      if (lookahead == '\\') ADVANCE(49);
      if (lookahead == ']') ADVANCE(47);
      if (lookahead == 'a') ADVANCE(46);
      if (lookahead == 'b') ADVANCE(48);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym__char_token1);
      if (lookahead == '\\') ADVANCE(43);
      if (lookahead == ']') ADVANCE(39);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(44);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(41);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym__char_token1);
      if (lookahead == '\\') ADVANCE(43);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(45);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(41);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_escape_token1);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_escape_token2);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_escape_token3);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_escape_token4);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym__code_token1);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym__code_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(53);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(52);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 11},
  [2] = {.lex_state = 11},
  [3] = {.lex_state = 11},
  [4] = {.lex_state = 11},
  [5] = {.lex_state = 11},
  [6] = {.lex_state = 11},
  [7] = {.lex_state = 11},
  [8] = {.lex_state = 11},
  [9] = {.lex_state = 11},
  [10] = {.lex_state = 11},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 11},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 11},
  [16] = {.lex_state = 11},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 11},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 11},
  [22] = {.lex_state = 11},
  [23] = {.lex_state = 11},
  [24] = {.lex_state = 11},
  [25] = {.lex_state = 11},
  [26] = {.lex_state = 11},
  [27] = {.lex_state = 11},
  [28] = {.lex_state = 11},
  [29] = {.lex_state = 11},
  [30] = {.lex_state = 11},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 11},
  [37] = {.lex_state = 11},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 3},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 3},
  [42] = {.lex_state = 2},
  [43] = {.lex_state = 11},
  [44] = {.lex_state = 11},
  [45] = {.lex_state = 11},
  [46] = {.lex_state = 2},
  [47] = {.lex_state = 11},
  [48] = {.lex_state = 11},
  [49] = {.lex_state = 10},
  [50] = {.lex_state = 10},
  [51] = {.lex_state = 11},
  [52] = {.lex_state = 11},
  [53] = {.lex_state = 10},
  [54] = {.lex_state = 10},
  [55] = {.lex_state = 11},
  [56] = {.lex_state = 10},
  [57] = {.lex_state = 11},
  [58] = {.lex_state = 11},
  [59] = {.lex_state = 11},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 8},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 5},
  [64] = {.lex_state = 5},
  [65] = {.lex_state = 6},
  [66] = {.lex_state = 5},
  [67] = {.lex_state = 5},
  [68] = {.lex_state = 8},
  [69] = {.lex_state = 6},
  [70] = {.lex_state = 10},
  [71] = {.lex_state = 6},
  [72] = {.lex_state = 6},
  [73] = {.lex_state = 5},
  [74] = {.lex_state = 8},
  [75] = {.lex_state = 6},
  [76] = {.lex_state = 8},
  [77] = {.lex_state = 8},
  [78] = {.lex_state = 10},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 4},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 14},
  [86] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SLASH_SLASH] = ACTIONS(1),
    [anon_sym_LT_DASH] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_i] = ACTIONS(1),
    [aux_sym__sq_string_literal_token1] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [aux_sym_escape_token1] = ACTIONS(1),
    [aux_sym_escape_token2] = ACTIONS(1),
    [aux_sym_escape_token3] = ACTIONS(1),
    [aux_sym_escape_token4] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
  },
  [1] = {
    [sym_grammar] = STATE(81),
    [sym_comment] = STATE(36),
    [sym_definition] = STATE(36),
    [sym_action] = STATE(36),
    [aux_sym_grammar_repeat1] = STATE(36),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym_identifier] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 17,
    ACTIONS(11), 1,
      anon_sym_SLASH,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_DOT,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(22), 1,
      aux_sym__sq_string_literal_token1,
    ACTIONS(24), 1,
      anon_sym_DQUOTE,
    ACTIONS(26), 1,
      anon_sym_LBRACK,
    ACTIONS(28), 1,
      anon_sym_LBRACE,
    STATE(19), 1,
      sym_alias,
    STATE(24), 1,
      sym_primary,
    STATE(29), 1,
      sym_prefix,
    STATE(52), 1,
      sym_action,
    ACTIONS(9), 2,
      ts_builtin_sym_end,
      anon_sym_SLASH_SLASH,
    ACTIONS(13), 2,
      anon_sym_AMP,
      anon_sym_BANG,
    STATE(3), 2,
      sym_term,
      aux_sym__sequence_repeat1,
    STATE(11), 2,
      sym__sq_string_literal,
      sym__dq_string_literal,
    STATE(25), 2,
      sym_literal,
      sym_class,
  [57] = 15,
    ACTIONS(33), 1,
      anon_sym_SLASH,
    ACTIONS(38), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 1,
      anon_sym_DOT,
    ACTIONS(44), 1,
      sym_identifier,
    ACTIONS(47), 1,
      aux_sym__sq_string_literal_token1,
    ACTIONS(50), 1,
      anon_sym_DQUOTE,
    ACTIONS(53), 1,
      anon_sym_LBRACK,
    STATE(19), 1,
      sym_alias,
    STATE(24), 1,
      sym_primary,
    STATE(29), 1,
      sym_prefix,
    ACTIONS(35), 2,
      anon_sym_AMP,
      anon_sym_BANG,
    STATE(3), 2,
      sym_term,
      aux_sym__sequence_repeat1,
    STATE(11), 2,
      sym__sq_string_literal,
      sym__dq_string_literal,
    STATE(25), 2,
      sym_literal,
      sym_class,
    ACTIONS(31), 4,
      ts_builtin_sym_end,
      anon_sym_SLASH_SLASH,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
  [110] = 16,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_DOT,
    ACTIONS(22), 1,
      aux_sym__sq_string_literal_token1,
    ACTIONS(24), 1,
      anon_sym_DQUOTE,
    ACTIONS(26), 1,
      anon_sym_LBRACK,
    ACTIONS(56), 1,
      anon_sym_SLASH,
    ACTIONS(58), 1,
      anon_sym_RPAREN,
    ACTIONS(60), 1,
      sym_identifier,
    STATE(19), 1,
      sym_alias,
    STATE(24), 1,
      sym_primary,
    STATE(29), 1,
      sym_prefix,
    STATE(62), 1,
      aux_sym_e_repeat1,
    ACTIONS(13), 2,
      anon_sym_AMP,
      anon_sym_BANG,
    STATE(3), 2,
      sym_term,
      aux_sym__sequence_repeat1,
    STATE(11), 2,
      sym__sq_string_literal,
      sym__dq_string_literal,
    STATE(25), 2,
      sym_literal,
      sym_class,
  [163] = 15,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_DOT,
    ACTIONS(22), 1,
      aux_sym__sq_string_literal_token1,
    ACTIONS(24), 1,
      anon_sym_DQUOTE,
    ACTIONS(26), 1,
      anon_sym_LBRACK,
    ACTIONS(60), 1,
      sym_identifier,
    STATE(19), 1,
      sym_alias,
    STATE(24), 1,
      sym_primary,
    STATE(29), 1,
      sym_prefix,
    STATE(44), 1,
      sym__sequence,
    STATE(59), 1,
      sym_expression,
    ACTIONS(13), 2,
      anon_sym_AMP,
      anon_sym_BANG,
    STATE(2), 2,
      sym_term,
      aux_sym__sequence_repeat1,
    STATE(11), 2,
      sym__sq_string_literal,
      sym__dq_string_literal,
    STATE(25), 2,
      sym_literal,
      sym_class,
  [213] = 15,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_DOT,
    ACTIONS(22), 1,
      aux_sym__sq_string_literal_token1,
    ACTIONS(24), 1,
      anon_sym_DQUOTE,
    ACTIONS(26), 1,
      anon_sym_LBRACK,
    ACTIONS(60), 1,
      sym_identifier,
    STATE(19), 1,
      sym_alias,
    STATE(24), 1,
      sym_primary,
    STATE(29), 1,
      sym_prefix,
    STATE(44), 1,
      sym__sequence,
    STATE(57), 1,
      sym_expression,
    ACTIONS(13), 2,
      anon_sym_AMP,
      anon_sym_BANG,
    STATE(2), 2,
      sym_term,
      aux_sym__sequence_repeat1,
    STATE(11), 2,
      sym__sq_string_literal,
      sym__dq_string_literal,
    STATE(25), 2,
      sym_literal,
      sym_class,
  [263] = 14,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_DOT,
    ACTIONS(22), 1,
      aux_sym__sq_string_literal_token1,
    ACTIONS(24), 1,
      anon_sym_DQUOTE,
    ACTIONS(26), 1,
      anon_sym_LBRACK,
    ACTIONS(60), 1,
      sym_identifier,
    STATE(19), 1,
      sym_alias,
    STATE(24), 1,
      sym_primary,
    STATE(29), 1,
      sym_prefix,
    ACTIONS(13), 2,
      anon_sym_AMP,
      anon_sym_BANG,
    ACTIONS(62), 2,
      anon_sym_SLASH,
      anon_sym_RPAREN,
    STATE(3), 2,
      sym_term,
      aux_sym__sequence_repeat1,
    STATE(11), 2,
      sym__sq_string_literal,
      sym__dq_string_literal,
    STATE(25), 2,
      sym_literal,
      sym_class,
  [311] = 2,
    ACTIONS(66), 1,
      anon_sym_SLASH,
    ACTIONS(64), 17,
      ts_builtin_sym_end,
      anon_sym_SLASH_SLASH,
      anon_sym_LT_DASH,
      anon_sym_EQ,
      anon_sym_AMP,
      anon_sym_BANG,
      anon_sym_QMARK,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DOT,
      sym_identifier,
      aux_sym__sq_string_literal_token1,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
  [334] = 14,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_DOT,
    ACTIONS(22), 1,
      aux_sym__sq_string_literal_token1,
    ACTIONS(24), 1,
      anon_sym_DQUOTE,
    ACTIONS(26), 1,
      anon_sym_LBRACK,
    ACTIONS(60), 1,
      sym_identifier,
    STATE(19), 1,
      sym_alias,
    STATE(24), 1,
      sym_primary,
    STATE(29), 1,
      sym_prefix,
    STATE(55), 1,
      sym__sequence,
    ACTIONS(13), 2,
      anon_sym_AMP,
      anon_sym_BANG,
    STATE(2), 2,
      sym_term,
      aux_sym__sequence_repeat1,
    STATE(11), 2,
      sym__sq_string_literal,
      sym__dq_string_literal,
    STATE(25), 2,
      sym_literal,
      sym_class,
  [381] = 14,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_DOT,
    ACTIONS(22), 1,
      aux_sym__sq_string_literal_token1,
    ACTIONS(24), 1,
      anon_sym_DQUOTE,
    ACTIONS(26), 1,
      anon_sym_LBRACK,
    ACTIONS(60), 1,
      sym_identifier,
    STATE(19), 1,
      sym_alias,
    STATE(24), 1,
      sym_primary,
    STATE(29), 1,
      sym_prefix,
    STATE(80), 1,
      sym_e,
    ACTIONS(13), 2,
      anon_sym_AMP,
      anon_sym_BANG,
    STATE(4), 2,
      sym_term,
      aux_sym__sequence_repeat1,
    STATE(11), 2,
      sym__sq_string_literal,
      sym__dq_string_literal,
    STATE(25), 2,
      sym_literal,
      sym_class,
  [428] = 3,
    ACTIONS(72), 1,
      anon_sym_i,
    ACTIONS(70), 2,
      anon_sym_SLASH,
      sym_identifier,
    ACTIONS(68), 14,
      ts_builtin_sym_end,
      anon_sym_SLASH_SLASH,
      anon_sym_AMP,
      anon_sym_BANG,
      anon_sym_QMARK,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DOT,
      aux_sym__sq_string_literal_token1,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
  [452] = 3,
    ACTIONS(78), 1,
      anon_sym_i,
    ACTIONS(76), 2,
      anon_sym_SLASH,
      sym_identifier,
    ACTIONS(74), 14,
      ts_builtin_sym_end,
      anon_sym_SLASH_SLASH,
      anon_sym_AMP,
      anon_sym_BANG,
      anon_sym_QMARK,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DOT,
      aux_sym__sq_string_literal_token1,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
  [476] = 13,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_DOT,
    ACTIONS(22), 1,
      aux_sym__sq_string_literal_token1,
    ACTIONS(24), 1,
      anon_sym_DQUOTE,
    ACTIONS(26), 1,
      anon_sym_LBRACK,
    ACTIONS(60), 1,
      sym_identifier,
    STATE(19), 1,
      sym_alias,
    STATE(24), 1,
      sym_primary,
    STATE(29), 1,
      sym_prefix,
    ACTIONS(13), 2,
      anon_sym_AMP,
      anon_sym_BANG,
    STATE(7), 2,
      sym_term,
      aux_sym__sequence_repeat1,
    STATE(11), 2,
      sym__sq_string_literal,
      sym__dq_string_literal,
    STATE(25), 2,
      sym_literal,
      sym_class,
  [520] = 2,
    ACTIONS(82), 3,
      anon_sym_SLASH,
      sym_identifier,
      anon_sym_i,
    ACTIONS(80), 14,
      ts_builtin_sym_end,
      anon_sym_SLASH_SLASH,
      anon_sym_AMP,
      anon_sym_BANG,
      anon_sym_QMARK,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DOT,
      aux_sym__sq_string_literal_token1,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
  [542] = 4,
    ACTIONS(86), 1,
      anon_sym_SLASH,
    STATE(28), 1,
      sym_suffix,
    ACTIONS(88), 3,
      anon_sym_QMARK,
      anon_sym_STAR,
      anon_sym_PLUS,
    ACTIONS(84), 12,
      ts_builtin_sym_end,
      anon_sym_SLASH_SLASH,
      anon_sym_AMP,
      anon_sym_BANG,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DOT,
      sym_identifier,
      aux_sym__sq_string_literal_token1,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
  [568] = 3,
    ACTIONS(92), 1,
      anon_sym_SLASH,
    ACTIONS(94), 1,
      anon_sym_COLON,
    ACTIONS(90), 15,
      ts_builtin_sym_end,
      anon_sym_SLASH_SLASH,
      anon_sym_AMP,
      anon_sym_BANG,
      anon_sym_QMARK,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DOT,
      sym_identifier,
      aux_sym__sq_string_literal_token1,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
  [592] = 2,
    ACTIONS(98), 3,
      anon_sym_SLASH,
      sym_identifier,
      anon_sym_i,
    ACTIONS(96), 14,
      ts_builtin_sym_end,
      anon_sym_SLASH_SLASH,
      anon_sym_AMP,
      anon_sym_BANG,
      anon_sym_QMARK,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DOT,
      aux_sym__sq_string_literal_token1,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
  [614] = 2,
    ACTIONS(102), 3,
      anon_sym_SLASH,
      sym_identifier,
      anon_sym_i,
    ACTIONS(100), 14,
      ts_builtin_sym_end,
      anon_sym_SLASH_SLASH,
      anon_sym_AMP,
      anon_sym_BANG,
      anon_sym_QMARK,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DOT,
      aux_sym__sq_string_literal_token1,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
  [636] = 4,
    ACTIONS(106), 1,
      anon_sym_SLASH,
    STATE(27), 1,
      sym_suffix,
    ACTIONS(88), 3,
      anon_sym_QMARK,
      anon_sym_STAR,
      anon_sym_PLUS,
    ACTIONS(104), 12,
      ts_builtin_sym_end,
      anon_sym_SLASH_SLASH,
      anon_sym_AMP,
      anon_sym_BANG,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DOT,
      sym_identifier,
      aux_sym__sq_string_literal_token1,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
  [662] = 2,
    ACTIONS(110), 3,
      anon_sym_SLASH,
      sym_identifier,
      anon_sym_i,
    ACTIONS(108), 14,
      ts_builtin_sym_end,
      anon_sym_SLASH_SLASH,
      anon_sym_AMP,
      anon_sym_BANG,
      anon_sym_QMARK,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DOT,
      aux_sym__sq_string_literal_token1,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
  [684] = 2,
    ACTIONS(114), 1,
      anon_sym_SLASH,
    ACTIONS(112), 15,
      ts_builtin_sym_end,
      anon_sym_SLASH_SLASH,
      anon_sym_AMP,
      anon_sym_BANG,
      anon_sym_QMARK,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DOT,
      sym_identifier,
      aux_sym__sq_string_literal_token1,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
  [705] = 2,
    ACTIONS(118), 1,
      anon_sym_SLASH,
    ACTIONS(116), 15,
      ts_builtin_sym_end,
      anon_sym_SLASH_SLASH,
      anon_sym_AMP,
      anon_sym_BANG,
      anon_sym_QMARK,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DOT,
      sym_identifier,
      aux_sym__sq_string_literal_token1,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
  [726] = 2,
    ACTIONS(122), 1,
      anon_sym_SLASH,
    ACTIONS(120), 15,
      ts_builtin_sym_end,
      anon_sym_SLASH_SLASH,
      anon_sym_AMP,
      anon_sym_BANG,
      anon_sym_QMARK,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DOT,
      sym_identifier,
      aux_sym__sq_string_literal_token1,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
  [747] = 2,
    ACTIONS(126), 1,
      anon_sym_SLASH,
    ACTIONS(124), 15,
      ts_builtin_sym_end,
      anon_sym_SLASH_SLASH,
      anon_sym_AMP,
      anon_sym_BANG,
      anon_sym_QMARK,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DOT,
      sym_identifier,
      aux_sym__sq_string_literal_token1,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
  [768] = 2,
    ACTIONS(92), 1,
      anon_sym_SLASH,
    ACTIONS(90), 15,
      ts_builtin_sym_end,
      anon_sym_SLASH_SLASH,
      anon_sym_AMP,
      anon_sym_BANG,
      anon_sym_QMARK,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DOT,
      sym_identifier,
      aux_sym__sq_string_literal_token1,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
  [789] = 2,
    ACTIONS(130), 1,
      anon_sym_SLASH,
    ACTIONS(128), 12,
      ts_builtin_sym_end,
      anon_sym_SLASH_SLASH,
      anon_sym_AMP,
      anon_sym_BANG,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DOT,
      sym_identifier,
      aux_sym__sq_string_literal_token1,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
  [807] = 2,
    ACTIONS(134), 1,
      anon_sym_SLASH,
    ACTIONS(132), 12,
      ts_builtin_sym_end,
      anon_sym_SLASH_SLASH,
      anon_sym_AMP,
      anon_sym_BANG,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DOT,
      sym_identifier,
      aux_sym__sq_string_literal_token1,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
  [825] = 2,
    ACTIONS(138), 1,
      anon_sym_SLASH,
    ACTIONS(136), 12,
      ts_builtin_sym_end,
      anon_sym_SLASH_SLASH,
      anon_sym_AMP,
      anon_sym_BANG,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DOT,
      sym_identifier,
      aux_sym__sq_string_literal_token1,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
  [843] = 10,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_DOT,
    ACTIONS(22), 1,
      aux_sym__sq_string_literal_token1,
    ACTIONS(24), 1,
      anon_sym_DQUOTE,
    ACTIONS(26), 1,
      anon_sym_LBRACK,
    ACTIONS(60), 1,
      sym_identifier,
    STATE(15), 1,
      sym_alias,
    STATE(24), 1,
      sym_primary,
    STATE(11), 2,
      sym__sq_string_literal,
      sym__dq_string_literal,
    STATE(25), 2,
      sym_literal,
      sym_class,
  [876] = 8,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(22), 1,
      aux_sym__sq_string_literal_token1,
    ACTIONS(24), 1,
      anon_sym_DQUOTE,
    ACTIONS(26), 1,
      anon_sym_LBRACK,
    STATE(21), 1,
      sym_primary,
    ACTIONS(17), 2,
      anon_sym_DOT,
      sym_identifier,
    STATE(11), 2,
      sym__sq_string_literal,
      sym__dq_string_literal,
    STATE(25), 2,
      sym_literal,
      sym_class,
  [904] = 6,
    ACTIONS(140), 1,
      aux_sym__char_token1,
    STATE(32), 1,
      aux_sym__range_repeat2,
    STATE(33), 1,
      aux_sym__range_repeat1,
    STATE(84), 1,
      sym__range,
    STATE(39), 2,
      sym__char,
      sym_escape,
    ACTIONS(142), 4,
      aux_sym_escape_token1,
      aux_sym_escape_token2,
      aux_sym_escape_token3,
      aux_sym_escape_token4,
  [927] = 4,
    ACTIONS(144), 1,
      anon_sym_RBRACK,
    ACTIONS(146), 1,
      aux_sym__char_token1,
    STATE(34), 3,
      sym__char,
      sym_escape,
      aux_sym__range_repeat2,
    ACTIONS(148), 4,
      aux_sym_escape_token1,
      aux_sym_escape_token2,
      aux_sym_escape_token3,
      aux_sym_escape_token4,
  [945] = 5,
    ACTIONS(144), 1,
      anon_sym_RBRACK,
    ACTIONS(150), 1,
      aux_sym__char_token1,
    STATE(35), 1,
      aux_sym__range_repeat1,
    STATE(86), 2,
      sym__char,
      sym_escape,
    ACTIONS(152), 4,
      aux_sym_escape_token1,
      aux_sym_escape_token2,
      aux_sym_escape_token3,
      aux_sym_escape_token4,
  [965] = 4,
    ACTIONS(154), 1,
      anon_sym_RBRACK,
    ACTIONS(156), 1,
      aux_sym__char_token1,
    STATE(34), 3,
      sym__char,
      sym_escape,
      aux_sym__range_repeat2,
    ACTIONS(159), 4,
      aux_sym_escape_token1,
      aux_sym_escape_token2,
      aux_sym_escape_token3,
      aux_sym_escape_token4,
  [983] = 5,
    ACTIONS(162), 1,
      anon_sym_RBRACK,
    ACTIONS(164), 1,
      aux_sym__char_token1,
    STATE(35), 1,
      aux_sym__range_repeat1,
    STATE(86), 2,
      sym__char,
      sym_escape,
    ACTIONS(167), 4,
      aux_sym_escape_token1,
      aux_sym_escape_token2,
      aux_sym_escape_token3,
      aux_sym_escape_token4,
  [1003] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(170), 1,
      ts_builtin_sym_end,
    STATE(37), 4,
      sym_comment,
      sym_definition,
      sym_action,
      aux_sym_grammar_repeat1,
  [1022] = 5,
    ACTIONS(172), 1,
      ts_builtin_sym_end,
    ACTIONS(174), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(177), 1,
      sym_identifier,
    ACTIONS(180), 1,
      anon_sym_LBRACE,
    STATE(37), 4,
      sym_comment,
      sym_definition,
      sym_action,
      aux_sym_grammar_repeat1,
  [1041] = 5,
    ACTIONS(185), 1,
      aux_sym__sq_string_literal_token1,
    ACTIONS(187), 1,
      anon_sym_DQUOTE,
    STATE(79), 1,
      sym_literal,
    ACTIONS(183), 2,
      anon_sym_LT_DASH,
      anon_sym_EQ,
    STATE(61), 2,
      sym__sq_string_literal,
      sym__dq_string_literal,
  [1059] = 2,
    ACTIONS(191), 1,
      anon_sym_DASH,
    ACTIONS(189), 6,
      anon_sym_RBRACK,
      aux_sym__char_token1,
      aux_sym_escape_token1,
      aux_sym_escape_token2,
      aux_sym_escape_token3,
      aux_sym_escape_token4,
  [1071] = 3,
    ACTIONS(193), 1,
      aux_sym__char_token1,
    STATE(46), 2,
      sym__char,
      sym_escape,
    ACTIONS(148), 4,
      aux_sym_escape_token1,
      aux_sym_escape_token2,
      aux_sym_escape_token3,
      aux_sym_escape_token4,
  [1085] = 1,
    ACTIONS(195), 7,
      anon_sym_RBRACK,
      anon_sym_DASH,
      aux_sym__char_token1,
      aux_sym_escape_token1,
      aux_sym_escape_token2,
      aux_sym_escape_token3,
      aux_sym_escape_token4,
  [1095] = 1,
    ACTIONS(195), 6,
      anon_sym_RBRACK,
      aux_sym__char_token1,
      aux_sym_escape_token1,
      aux_sym_escape_token2,
      aux_sym_escape_token3,
      aux_sym_escape_token4,
  [1104] = 3,
    ACTIONS(199), 1,
      anon_sym_SLASH,
    STATE(45), 1,
      aux_sym_expression_repeat1,
    ACTIONS(197), 4,
      ts_builtin_sym_end,
      anon_sym_SLASH_SLASH,
      sym_identifier,
      anon_sym_LBRACE,
  [1117] = 3,
    ACTIONS(199), 1,
      anon_sym_SLASH,
    STATE(43), 1,
      aux_sym_expression_repeat1,
    ACTIONS(201), 4,
      ts_builtin_sym_end,
      anon_sym_SLASH_SLASH,
      sym_identifier,
      anon_sym_LBRACE,
  [1130] = 3,
    ACTIONS(205), 1,
      anon_sym_SLASH,
    STATE(45), 1,
      aux_sym_expression_repeat1,
    ACTIONS(203), 4,
      ts_builtin_sym_end,
      anon_sym_SLASH_SLASH,
      sym_identifier,
      anon_sym_LBRACE,
  [1143] = 1,
    ACTIONS(208), 6,
      anon_sym_RBRACK,
      aux_sym__char_token1,
      aux_sym_escape_token1,
      aux_sym_escape_token2,
      aux_sym_escape_token3,
      aux_sym_escape_token4,
  [1152] = 1,
    ACTIONS(210), 6,
      anon_sym_LPAREN,
      anon_sym_DOT,
      sym_identifier,
      aux_sym__sq_string_literal_token1,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
  [1161] = 2,
    ACTIONS(214), 1,
      anon_sym_SLASH,
    ACTIONS(212), 4,
      ts_builtin_sym_end,
      anon_sym_SLASH_SLASH,
      sym_identifier,
      anon_sym_LBRACE,
  [1171] = 4,
    ACTIONS(216), 1,
      anon_sym_LBRACE,
    ACTIONS(219), 1,
      anon_sym_RBRACE,
    ACTIONS(221), 1,
      aux_sym__code_token1,
    STATE(49), 2,
      sym__code,
      aux_sym_action_repeat1,
  [1185] = 4,
    ACTIONS(224), 1,
      anon_sym_LBRACE,
    ACTIONS(226), 1,
      anon_sym_RBRACE,
    ACTIONS(228), 1,
      aux_sym__code_token1,
    STATE(56), 2,
      sym__code,
      aux_sym_action_repeat1,
  [1199] = 2,
    ACTIONS(232), 1,
      anon_sym_SLASH,
    ACTIONS(230), 4,
      ts_builtin_sym_end,
      anon_sym_SLASH_SLASH,
      sym_identifier,
      anon_sym_LBRACE,
  [1209] = 2,
    ACTIONS(236), 1,
      anon_sym_SLASH,
    ACTIONS(234), 4,
      ts_builtin_sym_end,
      anon_sym_SLASH_SLASH,
      sym_identifier,
      anon_sym_LBRACE,
  [1219] = 4,
    ACTIONS(224), 1,
      anon_sym_LBRACE,
    ACTIONS(238), 1,
      anon_sym_RBRACE,
    ACTIONS(240), 1,
      aux_sym__code_token1,
    STATE(54), 2,
      sym__code,
      aux_sym_action_repeat1,
  [1233] = 4,
    ACTIONS(224), 1,
      anon_sym_LBRACE,
    ACTIONS(242), 1,
      anon_sym_RBRACE,
    ACTIONS(244), 1,
      aux_sym__code_token1,
    STATE(49), 2,
      sym__code,
      aux_sym_action_repeat1,
  [1247] = 2,
    ACTIONS(246), 1,
      anon_sym_SLASH,
    ACTIONS(203), 4,
      ts_builtin_sym_end,
      anon_sym_SLASH_SLASH,
      sym_identifier,
      anon_sym_LBRACE,
  [1257] = 4,
    ACTIONS(224), 1,
      anon_sym_LBRACE,
    ACTIONS(244), 1,
      aux_sym__code_token1,
    ACTIONS(248), 1,
      anon_sym_RBRACE,
    STATE(49), 2,
      sym__code,
      aux_sym_action_repeat1,
  [1271] = 1,
    ACTIONS(250), 4,
      ts_builtin_sym_end,
      anon_sym_SLASH_SLASH,
      sym_identifier,
      anon_sym_LBRACE,
  [1278] = 1,
    ACTIONS(252), 4,
      ts_builtin_sym_end,
      anon_sym_SLASH_SLASH,
      sym_identifier,
      anon_sym_LBRACE,
  [1285] = 1,
    ACTIONS(254), 4,
      ts_builtin_sym_end,
      anon_sym_SLASH_SLASH,
      sym_identifier,
      anon_sym_LBRACE,
  [1292] = 3,
    ACTIONS(62), 1,
      anon_sym_RPAREN,
    ACTIONS(256), 1,
      anon_sym_SLASH,
    STATE(60), 1,
      aux_sym_e_repeat1,
  [1302] = 2,
    ACTIONS(259), 1,
      anon_sym_i,
    ACTIONS(68), 2,
      anon_sym_LT_DASH,
      anon_sym_EQ,
  [1310] = 3,
    ACTIONS(56), 1,
      anon_sym_SLASH,
    ACTIONS(261), 1,
      anon_sym_RPAREN,
    STATE(60), 1,
      aux_sym_e_repeat1,
  [1320] = 3,
    ACTIONS(263), 1,
      anon_sym_DQUOTE,
    ACTIONS(265), 1,
      aux_sym__dq_string_literal_token1,
    STATE(73), 1,
      aux_sym__dq_string_literal_repeat1,
  [1330] = 3,
    ACTIONS(267), 1,
      anon_sym_DQUOTE,
    ACTIONS(269), 1,
      aux_sym__dq_string_literal_token1,
    STATE(67), 1,
      aux_sym__dq_string_literal_repeat1,
  [1340] = 3,
    ACTIONS(271), 1,
      aux_sym__sq_string_literal_token1,
    ACTIONS(273), 1,
      aux_sym__sq_string_literal_token2,
    STATE(69), 1,
      aux_sym__sq_string_literal_repeat1,
  [1350] = 3,
    ACTIONS(275), 1,
      anon_sym_DQUOTE,
    ACTIONS(277), 1,
      aux_sym__dq_string_literal_token1,
    STATE(64), 1,
      aux_sym__dq_string_literal_repeat1,
  [1360] = 3,
    ACTIONS(279), 1,
      anon_sym_DQUOTE,
    ACTIONS(281), 1,
      aux_sym__dq_string_literal_token1,
    STATE(67), 1,
      aux_sym__dq_string_literal_repeat1,
  [1370] = 1,
    ACTIONS(80), 3,
      anon_sym_LT_DASH,
      anon_sym_EQ,
      anon_sym_i,
  [1376] = 3,
    ACTIONS(284), 1,
      aux_sym__sq_string_literal_token1,
    ACTIONS(286), 1,
      aux_sym__sq_string_literal_token2,
    STATE(69), 1,
      aux_sym__sq_string_literal_repeat1,
  [1386] = 2,
    ACTIONS(291), 1,
      aux_sym__code_token1,
    ACTIONS(289), 2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1394] = 3,
    ACTIONS(293), 1,
      aux_sym__sq_string_literal_token1,
    ACTIONS(295), 1,
      aux_sym__sq_string_literal_token2,
    STATE(75), 1,
      aux_sym__sq_string_literal_repeat1,
  [1404] = 3,
    ACTIONS(297), 1,
      aux_sym__sq_string_literal_token1,
    ACTIONS(299), 1,
      aux_sym__sq_string_literal_token2,
    STATE(65), 1,
      aux_sym__sq_string_literal_repeat1,
  [1414] = 3,
    ACTIONS(269), 1,
      aux_sym__dq_string_literal_token1,
    ACTIONS(301), 1,
      anon_sym_DQUOTE,
    STATE(67), 1,
      aux_sym__dq_string_literal_repeat1,
  [1424] = 1,
    ACTIONS(100), 3,
      anon_sym_LT_DASH,
      anon_sym_EQ,
      anon_sym_i,
  [1430] = 3,
    ACTIONS(273), 1,
      aux_sym__sq_string_literal_token2,
    ACTIONS(303), 1,
      aux_sym__sq_string_literal_token1,
    STATE(69), 1,
      aux_sym__sq_string_literal_repeat1,
  [1440] = 1,
    ACTIONS(108), 3,
      anon_sym_LT_DASH,
      anon_sym_EQ,
      anon_sym_i,
  [1446] = 1,
    ACTIONS(96), 3,
      anon_sym_LT_DASH,
      anon_sym_EQ,
      anon_sym_i,
  [1452] = 2,
    ACTIONS(307), 1,
      aux_sym__code_token1,
    ACTIONS(305), 2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1460] = 1,
    ACTIONS(309), 2,
      anon_sym_LT_DASH,
      anon_sym_EQ,
  [1465] = 1,
    ACTIONS(311), 1,
      anon_sym_RPAREN,
  [1469] = 1,
    ACTIONS(313), 1,
      ts_builtin_sym_end,
  [1473] = 1,
    ACTIONS(315), 1,
      anon_sym_DASH,
  [1477] = 1,
    ACTIONS(317), 1,
      aux_sym_comment_token2,
  [1481] = 1,
    ACTIONS(319), 1,
      anon_sym_RBRACK,
  [1485] = 1,
    ACTIONS(321), 1,
      aux_sym_comment_token1,
  [1489] = 1,
    ACTIONS(323), 1,
      anon_sym_DASH,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 57,
  [SMALL_STATE(4)] = 110,
  [SMALL_STATE(5)] = 163,
  [SMALL_STATE(6)] = 213,
  [SMALL_STATE(7)] = 263,
  [SMALL_STATE(8)] = 311,
  [SMALL_STATE(9)] = 334,
  [SMALL_STATE(10)] = 381,
  [SMALL_STATE(11)] = 428,
  [SMALL_STATE(12)] = 452,
  [SMALL_STATE(13)] = 476,
  [SMALL_STATE(14)] = 520,
  [SMALL_STATE(15)] = 542,
  [SMALL_STATE(16)] = 568,
  [SMALL_STATE(17)] = 592,
  [SMALL_STATE(18)] = 614,
  [SMALL_STATE(19)] = 636,
  [SMALL_STATE(20)] = 662,
  [SMALL_STATE(21)] = 684,
  [SMALL_STATE(22)] = 705,
  [SMALL_STATE(23)] = 726,
  [SMALL_STATE(24)] = 747,
  [SMALL_STATE(25)] = 768,
  [SMALL_STATE(26)] = 789,
  [SMALL_STATE(27)] = 807,
  [SMALL_STATE(28)] = 825,
  [SMALL_STATE(29)] = 843,
  [SMALL_STATE(30)] = 876,
  [SMALL_STATE(31)] = 904,
  [SMALL_STATE(32)] = 927,
  [SMALL_STATE(33)] = 945,
  [SMALL_STATE(34)] = 965,
  [SMALL_STATE(35)] = 983,
  [SMALL_STATE(36)] = 1003,
  [SMALL_STATE(37)] = 1022,
  [SMALL_STATE(38)] = 1041,
  [SMALL_STATE(39)] = 1059,
  [SMALL_STATE(40)] = 1071,
  [SMALL_STATE(41)] = 1085,
  [SMALL_STATE(42)] = 1095,
  [SMALL_STATE(43)] = 1104,
  [SMALL_STATE(44)] = 1117,
  [SMALL_STATE(45)] = 1130,
  [SMALL_STATE(46)] = 1143,
  [SMALL_STATE(47)] = 1152,
  [SMALL_STATE(48)] = 1161,
  [SMALL_STATE(49)] = 1171,
  [SMALL_STATE(50)] = 1185,
  [SMALL_STATE(51)] = 1199,
  [SMALL_STATE(52)] = 1209,
  [SMALL_STATE(53)] = 1219,
  [SMALL_STATE(54)] = 1233,
  [SMALL_STATE(55)] = 1247,
  [SMALL_STATE(56)] = 1257,
  [SMALL_STATE(57)] = 1271,
  [SMALL_STATE(58)] = 1278,
  [SMALL_STATE(59)] = 1285,
  [SMALL_STATE(60)] = 1292,
  [SMALL_STATE(61)] = 1302,
  [SMALL_STATE(62)] = 1310,
  [SMALL_STATE(63)] = 1320,
  [SMALL_STATE(64)] = 1330,
  [SMALL_STATE(65)] = 1340,
  [SMALL_STATE(66)] = 1350,
  [SMALL_STATE(67)] = 1360,
  [SMALL_STATE(68)] = 1370,
  [SMALL_STATE(69)] = 1376,
  [SMALL_STATE(70)] = 1386,
  [SMALL_STATE(71)] = 1394,
  [SMALL_STATE(72)] = 1404,
  [SMALL_STATE(73)] = 1414,
  [SMALL_STATE(74)] = 1424,
  [SMALL_STATE(75)] = 1430,
  [SMALL_STATE(76)] = 1440,
  [SMALL_STATE(77)] = 1446,
  [SMALL_STATE(78)] = 1452,
  [SMALL_STATE(79)] = 1460,
  [SMALL_STATE(80)] = 1465,
  [SMALL_STATE(81)] = 1469,
  [SMALL_STATE(82)] = 1473,
  [SMALL_STATE(83)] = 1477,
  [SMALL_STATE(84)] = 1481,
  [SMALL_STATE(85)] = 1485,
  [SMALL_STATE(86)] = 1489,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__sequence, 1),
  [11] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__sequence, 1),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [19] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym__sequence, 1), SHIFT(16),
  [22] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [24] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [26] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym__sequence, 1), SHIFT(50),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__sequence_repeat1, 2),
  [33] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__sequence_repeat1, 2),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__sequence_repeat1, 2), SHIFT_REPEAT(47),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__sequence_repeat1, 2), SHIFT_REPEAT(10),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__sequence_repeat1, 2), SHIFT_REPEAT(25),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__sequence_repeat1, 2), SHIFT_REPEAT(16),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__sequence_repeat1, 2), SHIFT_REPEAT(72),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__sequence_repeat1, 2), SHIFT_REPEAT(66),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__sequence_repeat1, 2), SHIFT_REPEAT(31),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_e, 1),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_e_repeat1, 2),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 2),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_literal, 2),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 1),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_literal, 1),
  [72] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class, 3),
  [76] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_class, 3),
  [78] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__dq_string_literal, 3),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__dq_string_literal, 3),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term, 2, .production_id = 4),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_term, 2, .production_id = 4),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primary, 1),
  [92] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_primary, 1),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__sq_string_literal, 2),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__sq_string_literal, 2),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__dq_string_literal, 2),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__dq_string_literal, 2),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term, 1, .production_id = 2),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_term, 1, .production_id = 2),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__sq_string_literal, 3),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__sq_string_literal, 3),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alias, 3),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_alias, 3),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primary, 3),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_primary, 3),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class, 4),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_class, 4),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alias, 1),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_alias, 1),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_suffix, 1),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_suffix, 1),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term, 2, .production_id = 3),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_term, 2, .production_id = 3),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term, 3, .production_id = 6),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_term, 3, .production_id = 6),
  [140] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [142] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__range, 1),
  [146] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [148] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [150] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [152] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__range_repeat2, 2),
  [156] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__range_repeat2, 2), SHIFT_REPEAT(34),
  [159] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__range_repeat2, 2), SHIFT_REPEAT(42),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__range_repeat1, 2),
  [164] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__range_repeat1, 2), SHIFT_REPEAT(86),
  [167] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__range_repeat1, 2), SHIFT_REPEAT(82),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grammar, 1),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_grammar_repeat1, 2),
  [174] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_grammar_repeat1, 2), SHIFT_REPEAT(85),
  [177] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_grammar_repeat1, 2), SHIFT_REPEAT(38),
  [180] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_grammar_repeat1, 2), SHIFT_REPEAT(50),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [189] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__range_repeat2, 1),
  [191] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [193] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [195] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_escape, 1),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 2),
  [199] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_expression_repeat1, 2),
  [205] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_expression_repeat1, 2), SHIFT_REPEAT(9),
  [208] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__range_repeat1, 3),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prefix, 1),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_action, 3),
  [214] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_action, 3),
  [216] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_action_repeat1, 2), SHIFT_REPEAT(53),
  [219] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_action_repeat1, 2),
  [221] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_action_repeat1, 2), SHIFT_REPEAT(49),
  [224] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [226] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_action, 2),
  [232] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_action, 2),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__sequence, 2),
  [236] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__sequence, 2),
  [238] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [242] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [246] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_expression_repeat1, 2),
  [248] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [250] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_definition, 4, .production_id = 5),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3),
  [254] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_definition, 3, .production_id = 1),
  [256] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_e_repeat1, 2), SHIFT_REPEAT(13),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [261] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_e, 2),
  [263] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [267] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [271] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [275] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [279] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__dq_string_literal_repeat1, 2),
  [281] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__dq_string_literal_repeat1, 2), SHIFT_REPEAT(67),
  [284] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__sq_string_literal_repeat1, 2),
  [286] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__sq_string_literal_repeat1, 2), SHIFT_REPEAT(69),
  [289] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__code, 2),
  [291] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__code, 2),
  [293] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [297] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [301] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [303] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [305] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__code, 3),
  [307] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__code, 3),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [313] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [315] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_escape, 1),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_peg(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
